name: Build Artifacts
on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      channel:
        required: false
        default: stable
        type: string
      windows:
        default: true
        type: boolean
      meta_files:
        default: false
        type: boolean
    secrets:
      GPG_SIGNING_KEY:
        required: false

  workflow_dispatch:
    inputs:
      version:
        description: Version tag (YYYY.MM.DD[.REV])
        required: true
        type: string
      channel:
        description: Update channel (stable/nightly)
        required: true
        default: stable
        type: string
      windows:
        description: yt-dlp.exe
        default: true
        type: boolean

permissions:
  contents: read

jobs:
  windows:
    if: inputs.windows
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install Requirements
        run: | # Custom pyinstaller built with https://github.com/yt-dlp/pyinstaller-builds
          python -m pip install -U pip setuptools wheel py2exe
          pip install -U "https://yt-dlp.github.io/Pyinstaller-Builds/x86_64/pyinstaller-5.8.0-py3-none-any.whl" -r requirements.txt

      - name: Prepare
        run: |
          python devscripts/update-version.py -c ${{ inputs.channel }} ${{ inputs.version }}
          python devscripts/make_lazy_extractors.py
      - name: Build
        run: |
          python setup.py py2exe
          Move-Item ./dist/yt-dlp.exe
          python pyinst.py
          python pyinst.py --onedir

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          path: |
            dist/yt-dlp.exe
